### ISSUE TITLE
Reproduce the mIoU for cityscapes

### ISSUE THREAD

**Issue by ftll574** [tzt101/CLADE#3]
Hello,
Thank you for making the code available.
I'm trying to reproduce the mIoU for cityscapes. I want to make sure how should I test the generated images using drn --ms.
What is the resolution when you calculate the mIoU using DRN ? do you upsample the genereted results before testing mIoU or downsample the labels?

Thanks again

**Comment by tzt101** [comment]
Hi, 
I use DRN (ptrained model: drn-d-105_ms_cityscapes.pth) to calculate the mIoU and Acc for cityscapes, but don't use --ms. The following error exists when using --ms:
Traceback (most recent call last):
  File "segment.py", line 824, in <module>
    main()
  File "segment.py", line 818, in main
    test_seg(args)
  File "segment.py", line 686, in test_seg
    scales=scales)
  File "segment.py", line 610, in test_ms
    label = label.numpy()
AttributeError: 'tuple' object has no attribute 'numpy'

And we do not upsample the results, just use 256*512 and downsample the labels.

**Comment by ftll574** [comment]
Thanks.
