### ISSUE TITLE
Weights for cityscapes discriminator network

### ISSUE THREAD

**Issue by TobiasMei** [tzt101/CLADE#5]
Hello, 

can you share the weights for the discriminator used to train the cityscpaes model?

Thanks in advance.

**Comment by tzt101** [comment]
The weights of discriminator on the cityscapes dataset can be found in https://mailustceducn-my.sharepoint.com/:f:/g/personal/tzt_mail_ustc_edu_cn/EmTTw0bWo6BGis-kKfxPY7sBL7eSCiY8UrRV0__2OpjgdA?e=A33ecc
